# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Serverless Stack
email: contact@anoma.ly
description: > # this means to ignore newlines until "baseurl:"
  Building a Full-Stack App
  with Serverless and React
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://serverless-stack.com" # the base hostname & protocol for your site, e.g. http://example.com
logo: /assets/og-image.jpg

github_repo: "https://github.com/AnomalyInnovations/serverless-stack-com"
github_edit_prefix: "/edit/master/"
github_history_prefix: "/commits/master/"
github_issues_prefix: "/issues/"

sst_github_repo: "https://github.com/serverless-stack/serverless-stack"
backend_github_repo: "https://github.com/AnomalyInnovations/serverless-stack-demo-api"
frontend_github_repo: "https://github.com/AnomalyInnovations/serverless-stack-demo-client"
frontend_fb_login_github_repo: "https://github.com/AnomalyInnovations/serverless-stack-demo-fb-login-client"
frontend_user_mgmt_github_repo: "https://github.com/AnomalyInnovations/serverless-stack-demo-user-mgmt-client"
backend_ext_api_github_repo: "https://github.com/AnomalyInnovations/serverless-stack-demo-ext-api"
backend_ext_resources_github_repo: "https://github.com/AnomalyInnovations/serverless-stack-demo-ext-resources"

newsletter_signup_form: "https://emailoctopus.com/lists/1c11b9a8-1500-11e8-a3c9-06b79b628af2/forms/subscribe"

survey_url: "https://serverless-stack.typeform.com/to/xiPdCW"

google_analytics: "UA-3536629-11"

forum_url: "https://discourse.serverless-stack.com"
forum_thread_prefix: "/t/"
patreon_url: "https://www.patreon.com/serverless_stack"
github_sponsor_url: "https://github.com/sponsors/jayair"
twitter_url: "https://twitter.com/anomaly_inv"
sst_twitter_url: "https://twitter.com/ServerlessStack"
slack_invite_url: "https://join.slack.com/t/serverless-stack/shared_invite/zt-kqna615x-AFoTXvrglivZqJZcnTzKZA"

collections:
  chapters:
    output: true

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

# Front Matter defaults
defaults:
  - scope:
      path: ""
    values:
      image: /assets/og-image.jpg
